export const CAT_EMOJI: Record<string, string> = {
  'Music': '🎸', 'DJ & Electronic': '🎧', 'Hip Hop & R&B': '🎤', 'Jazz & Blues': '🎷',
  'Live Concerts & Festivals': '🎪', 'Fitness': '🏃', 'Yoga & Pilates': '🧘',
  'Running & Cycling': '🚴', 'Climbing & Hiking': '🧗', 'Combat Sports & CrossFit': '🥊',
  'Food & Drink': '🍺', 'Coffee & Brunch': '☕', 'Wine & Cocktails': '🍷',
  'Cooking & Culinary': '👨‍🍳', 'Street Food & Markets': '🌮', 'Tech & Coding': '💻',
  'Startups & Entrepreneurship': '🚀', 'AI & Innovation': '🤖', 'Gaming & Esports': '🎮',
  'Web3 & Crypto': '⛓', 'Outdoors & Adventure': '🥾', 'Hiking & Camping': '⛺',
  'Water Sports': '🏄', 'Snow Sports': '🎿', 'Arts & Culture': '🎨',
  'Photography & Film': '📷', 'Theatre & Comedy': '🎭', 'Fashion & Style': '👗',
  'Literature & Writing': '📚', 'Social & Parties': '🎉', 'Nightlife': '🌙',
  'Networking': '💼', 'Business & Finance': '📈', 'Wellness & Mindfulness': '🌿',
  'Dance & Movement': '💃', 'Spirituality': '✨', 'Volunteering & Activism': '🌱',
  'Education & Workshops': '🎓', 'Sports & Recreation': '⚽', 'Pets & Animals': '🐾',
  'Science & Innovation': '🔬', 'Markets & Pop-ups': '🏪',
  'Tech': '💻', 'Outdoors': '🥾', 'Social': '🎉',
}
