export const CITIES = [
  { name: 'Bellingham', lat: 48.7519, lng: -122.4787 },
  { name: 'Bellevue', lat: 47.6101, lng: -122.2015 },
  { name: 'Seattle', lat: 47.6062, lng: -122.3321 },
  { name: 'Tacoma', lat: 47.2529, lng: -122.4443 },
  { name: 'Olympia', lat: 47.0379, lng: -122.9007 },
  { name: 'Portland', lat: 45.5051, lng: -122.6750 },
  { name: 'Vancouver', lat: 49.2827, lng: -123.1207 },
  { name: 'Victoria', lat: 48.4284, lng: -123.3656 },
]

export const CITY_NAMES = CITIES.map(c => c.name)

export const DEFAULT_CITY = CITIES[0]

export const getCityCoords = (cityName: string) =>
  CITIES.find(c => c.name === cityName) ?? DEFAULT_CITY

export const POPULAR_INTERESTS = [
  'music', 'hiking', 'coffee', 'food', 'fitness', 'art', 'tech', 'travel',
  'running', 'yoga', 'gaming', 'photography', 'cooking', 'nightlife',
  'startups', 'design', 'film', 'reading', 'sports', 'dancing',
  'networking', 'outdoors', 'wellness', 'volunteering',
]

export const ALL_INTERESTS = [
  'music', 'live music', 'concerts', 'festivals', 'dj', 'electronic', 'hip hop',
  'jazz', 'classical', 'indie', 'rock', 'r&b', 'pop', 'rap', 'karaoke',
  'film', 'movies', 'theatre', 'comedy', 'stand-up', 'podcasts', 'art',
  'photography', 'painting', 'drawing', 'ceramics', 'sculpture', 'fashion',
  'style', 'design', 'architecture', 'writing', 'poetry', 'books', 'reading',
  'history', 'museums',
  'food', 'coffee', 'wine', 'beer', 'cocktails', 'cooking', 'baking',
  'brunch', 'restaurants', 'street food', 'vegan', 'vegetarian', 'craft beer',
  'whiskey', 'tea',
  'fitness', 'running', 'gym', 'yoga', 'pilates', 'cycling', 'swimming',
  'rock climbing', 'martial arts', 'boxing', 'crossfit', 'wellness',
  'meditation', 'mental health', 'nutrition', 'dancing', 'salsa', 'bachata',
  'mindfulness',
  'outdoors', 'hiking', 'camping', 'surfing', 'skiing', 'snowboarding',
  'kayaking', 'travel', 'adventure', 'nature', 'gardening', 'birdwatching',
  'sustainability',
  'tech', 'startups', 'ai', 'crypto', 'coding', 'ux', 'product',
  'entrepreneurship', 'investing', 'web3', 'gaming', 'esports', 'science',
  'sports', 'football', 'basketball', 'soccer', 'tennis', 'golf', 'baseball',
  'hockey', 'volleyball', 'f1', 'motorsports', 'mma',
  'networking', 'volunteering', 'activism', 'community', 'nightlife',
  'parties', 'self-improvement', 'astrology', 'spirituality', 'languages',
  'pets', 'dogs', 'marketing', 'business',
]

export const EVENT_CATEGORIES = [
  'Music', 'DJ & Electronic', 'Hip Hop & R&B', 'Jazz & Blues', 'Live Concerts & Festivals',
  'Fitness', 'Yoga & Pilates', 'Running & Cycling', 'Climbing & Hiking', 'Combat Sports & CrossFit',
  'Food & Drink', 'Coffee & Brunch', 'Wine & Cocktails', 'Cooking & Culinary', 'Street Food & Markets',
  'Tech & Coding', 'Startups & Entrepreneurship', 'AI & Innovation', 'Gaming & Esports', 'Web3 & Crypto',
  'Outdoors & Adventure', 'Hiking & Camping', 'Water Sports', 'Snow Sports',
  'Arts & Culture', 'Photography & Film', 'Theatre & Comedy', 'Fashion & Style', 'Literature & Writing',
  'Social & Parties', 'Nightlife', 'Networking', 'Business & Finance',
  'Wellness & Mindfulness', 'Dance & Movement', 'Spirituality', 'Volunteering & Activism',
  'Education & Workshops', 'Sports & Recreation', 'Pets & Animals', 'Science & Innovation',
  'Markets & Pop-ups',
]

export const ALL_CITIES = [
  'Bellingham', 'Bellevue', 'Seattle', 'Tacoma', 'Olympia', 'Spokane',
  'Vancouver', 'Victoria', 'Surrey', 'Burnaby',
  'Portland', 'Eugene', 'Salem',
  'San Francisco', 'Los Angeles', 'San Diego', 'Sacramento',
  'New York', 'Brooklyn', 'Chicago', 'Austin', 'Denver',
  'Miami', 'Atlanta', 'Nashville', 'Boston', 'Philadelphia',
  'Minneapolis', 'Detroit', 'Phoenix', 'Las Vegas', 'Honolulu',
]

export const CAT_GRADIENT: Record<string, string> = {
  'Music': 'linear-gradient(135deg,#1E2E3A,#1A0E2A)',
  'DJ & Electronic': 'linear-gradient(135deg,#1A0E2A,#0E0A1E)',
  'Hip Hop & R&B': 'linear-gradient(135deg,#2A0E1A,#1A0E0E)',
  'Jazz & Blues': 'linear-gradient(135deg,#0E1A2A,#1A1E2A)',
  'Live Concerts & Festivals': 'linear-gradient(135deg,#1E1A2A,#2A1E0E)',
  'Fitness': 'linear-gradient(135deg,#2A1E0E,#1A2A0E)',
  'Yoga & Pilates': 'linear-gradient(135deg,#1A2A1A,#0E2A1A)',
  'Running & Cycling': 'linear-gradient(135deg,#2A2A0E,#1A2A0E)',
  'Climbing & Hiking': 'linear-gradient(135deg,#1A2A1A,#0E1A0E)',
  'Combat Sports & CrossFit': 'linear-gradient(135deg,#2A1A0E,#1A0E0E)',
  'Food & Drink': 'linear-gradient(135deg,#2A1A0E,#1E1A0E)',
  'Coffee & Brunch': 'linear-gradient(135deg,#2A1E0E,#1A1A0E)',
  'Wine & Cocktails': 'linear-gradient(135deg,#2A0E1A,#1A0E0E)',
  'Cooking & Culinary': 'linear-gradient(135deg,#2A1A0E,#2A0E0E)',
  'Street Food & Markets': 'linear-gradient(135deg,#2A1E0E,#1E2A0E)',
  'Tech & Coding': 'linear-gradient(135deg,#1A1E2A,#0E1A2A)',
  'Startups & Entrepreneurship': 'linear-gradient(135deg,#1E1A2A,#2A1A0E)',
  'AI & Innovation': 'linear-gradient(135deg,#0E1A2A,#1A0E2A)',
  'Gaming & Esports': 'linear-gradient(135deg,#1A0E2A,#0E0A1E)',
  'Web3 & Crypto': 'linear-gradient(135deg,#1A1E0E,#0E1A2A)',
  'Outdoors & Adventure': 'linear-gradient(135deg,#1A2A1A,#0E2A1A)',
  'Hiking & Camping': 'linear-gradient(135deg,#1A2A1A,#0E1A0E)',
  'Water Sports': 'linear-gradient(135deg,#0E1A2A,#1A2A2A)',
  'Snow Sports': 'linear-gradient(135deg,#1A1E2A,#0E1A2A)',
  'Arts & Culture': 'linear-gradient(135deg,#2A1A2A,#1A0E1E)',
  'Photography & Film': 'linear-gradient(135deg,#1A1A1A,#2A1A0E)',
  'Theatre & Comedy': 'linear-gradient(135deg,#2A1A0E,#1A0E2A)',
  'Fashion & Style': 'linear-gradient(135deg,#2A0E1A,#1A0E2A)',
  'Literature & Writing': 'linear-gradient(135deg,#1A1E2A,#0E1A1A)',
  'Social & Parties': 'linear-gradient(135deg,#1E3A1E,#2A1A0E)',
  'Nightlife': 'linear-gradient(135deg,#1A0E2A,#0E0A1A)',
  'Networking': 'linear-gradient(135deg,#1E1A2A,#1A1E2A)',
  'Business & Finance': 'linear-gradient(135deg,#1A1E2A,#2A1A0E)',
  'Wellness & Mindfulness': 'linear-gradient(135deg,#1A2A1A,#2A2A0E)',
  'Dance & Movement': 'linear-gradient(135deg,#2A0E1A,#1A0E2A)',
  'Spirituality': 'linear-gradient(135deg,#1A0E2A,#2A1A0E)',
  'Volunteering & Activism': 'linear-gradient(135deg,#1A2A1A,#0E2A1A)',
  'Education & Workshops': 'linear-gradient(135deg,#1A1E2A,#0E1A2A)',
  'Sports & Recreation': 'linear-gradient(135deg,#1E2A0E,#2A1E0E)',
  'Pets & Animals': 'linear-gradient(135deg,#2A2A0E,#1A2A0E)',
  'Science & Innovation': 'linear-gradient(135deg,#0E1A2A,#1A1E2A)',
  'Markets & Pop-ups': 'linear-gradient(135deg,#2A1E0E,#1A2A0E)',
  'Tech': 'linear-gradient(135deg,#1A1E2A,#0E1A2A)',
  'Outdoors': 'linear-gradient(135deg,#1A2A1A,#0E2A1A)',
  'Social': 'linear-gradient(135deg,#1E3A1E,#2A1A0E)',
}

export const INTEREST_TO_CATS: Record<string, string[]> = {
  'music': ['Music', 'Live Concerts & Festivals'], 'live music': ['Music', 'Live Concerts & Festivals'],
  'concerts': ['Live Concerts & Festivals'], 'festivals': ['Live Concerts & Festivals'],
  'dj': ['DJ & Electronic'], 'electronic': ['DJ & Electronic'], 'hip hop': ['Hip Hop & R&B'],
  'jazz': ['Jazz & Blues'], 'classical': ['Jazz & Blues'], 'indie': ['Music'], 'rock': ['Music'],
  'r&b': ['Hip Hop & R&B'], 'pop': ['Music'], 'rap': ['Hip Hop & R&B'], 'karaoke': ['Music', 'Social & Parties'],
  'film': ['Photography & Film'], 'movies': ['Photography & Film'], 'theatre': ['Theatre & Comedy'],
  'comedy': ['Theatre & Comedy'], 'stand-up': ['Theatre & Comedy'], 'podcasts': ['Tech & Coding', 'Social & Parties'],
  'art': ['Arts & Culture'], 'photography': ['Photography & Film'],
  'painting': ['Arts & Culture'], 'drawing': ['Arts & Culture'], 'ceramics': ['Arts & Culture'],
  'fashion': ['Fashion & Style'], 'design': ['Arts & Culture'], 'architecture': ['Arts & Culture'],
  'writing': ['Literature & Writing'], 'poetry': ['Literature & Writing'], 'books': ['Literature & Writing'],
  'reading': ['Literature & Writing'], 'history': ['Arts & Culture'], 'museums': ['Arts & Culture'],
  'food': ['Food & Drink', 'Street Food & Markets'], 'coffee': ['Coffee & Brunch'],
  'wine': ['Wine & Cocktails'], 'beer': ['Food & Drink', 'Wine & Cocktails'],
  'cocktails': ['Wine & Cocktails'], 'cooking': ['Cooking & Culinary'], 'baking': ['Cooking & Culinary'],
  'brunch': ['Coffee & Brunch'], 'restaurants': ['Food & Drink'], 'street food': ['Street Food & Markets'],
  'vegan': ['Cooking & Culinary'], 'vegetarian': ['Cooking & Culinary'],
  'craft beer': ['Wine & Cocktails'], 'whiskey': ['Wine & Cocktails'], 'tea': ['Coffee & Brunch'],
  'fitness': ['Fitness'], 'running': ['Running & Cycling'], 'gym': ['Fitness'],
  'yoga': ['Yoga & Pilates'], 'pilates': ['Yoga & Pilates'], 'cycling': ['Running & Cycling'],
  'swimming': ['Water Sports'], 'rock climbing': ['Climbing & Hiking'], 'martial arts': ['Combat Sports & CrossFit'],
  'boxing': ['Combat Sports & CrossFit'], 'crossfit': ['Combat Sports & CrossFit'],
  'wellness': ['Wellness & Mindfulness'], 'meditation': ['Wellness & Mindfulness'],
  'mental health': ['Wellness & Mindfulness'], 'nutrition': ['Cooking & Culinary'],
  'dancing': ['Dance & Movement'], 'salsa': ['Dance & Movement'], 'bachata': ['Dance & Movement'],
  'outdoors': ['Outdoors & Adventure'], 'hiking': ['Climbing & Hiking', 'Hiking & Camping'],
  'camping': ['Hiking & Camping'], 'surfing': ['Water Sports'], 'skiing': ['Snow Sports'],
  'snowboarding': ['Snow Sports'], 'kayaking': ['Water Sports'], 'travel': ['Outdoors & Adventure'],
  'adventure': ['Outdoors & Adventure'], 'nature': ['Outdoors & Adventure', 'Hiking & Camping'],
  'gardening': ['Volunteering & Activism'], 'birdwatching': ['Outdoors & Adventure'],
  'tech': ['Tech & Coding'], 'startups': ['Startups & Entrepreneurship'], 'ai': ['AI & Innovation'],
  'crypto': ['Web3 & Crypto'], 'coding': ['Tech & Coding'], 'ux': ['Tech & Coding'],
  'product': ['Startups & Entrepreneurship'], 'entrepreneurship': ['Startups & Entrepreneurship'],
  'investing': ['Business & Finance'], 'business': ['Business & Finance'], 'marketing': ['Business & Finance'],
  'web3': ['Web3 & Crypto'], 'gaming': ['Gaming & Esports'], 'esports': ['Gaming & Esports'],
  'sports': ['Sports & Recreation'], 'football': ['Sports & Recreation'], 'basketball': ['Sports & Recreation'],
  'soccer': ['Sports & Recreation'], 'tennis': ['Sports & Recreation'], 'golf': ['Sports & Recreation'],
  'baseball': ['Sports & Recreation'], 'hockey': ['Sports & Recreation'], 'volleyball': ['Sports & Recreation'],
  'f1': ['Sports & Recreation'], 'motorsports': ['Sports & Recreation'], 'mma': ['Combat Sports & CrossFit'],
  'networking': ['Networking'], 'volunteering': ['Volunteering & Activism'],
  'activism': ['Volunteering & Activism'], 'sustainability': ['Volunteering & Activism'],
  'community': ['Social & Parties', 'Volunteering & Activism'], 'nightlife': ['Nightlife'],
  'parties': ['Social & Parties'], 'mindfulness': ['Wellness & Mindfulness'],
  'self-improvement': ['Wellness & Mindfulness', 'Education & Workshops'],
  'astrology': ['Spirituality'], 'spirituality': ['Spirituality'], 'science': ['Science & Innovation'],
  'languages': ['Education & Workshops'], 'pets': ['Pets & Animals'], 'dogs': ['Pets & Animals'],
}
